### ISSUE TITLE
Rerouting subdomains to ports.

### ISSUE THREAD

**Issue by vvasuki** [vedavaapi/vedavaapi-misc#1]
शुभात्मभ्यो नमस्काराः।

मम कल्पनायां सुव्यवस्था स्याद् यदि vedavaapi.org यन्त्रे नाना सेवकाश् (servers) चलेयुः येषां सरलरीत्या उपक्षेत्रसङ्केतैर् (subdomains) उपयोगः स्यात्। यथा quotes.vedavaapi.org -> some scalara server running at port 1235, textract.vedavaapi.org -> flask server at port 9000, brat.vedavaapi.org -> brat server at 8001 etc.. भवतः को विचारः?

एतत् कथं व्यवस्थापनीयम् इति दर्शयतु, येन यथावकाशं कार्यान्तरे ऽपि कुर्यां प्रगतिम्।  [एतद्](http://stackoverflow.com/questions/12715195/how-to-forward-a-subdomain-to-a-new-port-on-the-same-ip-address) दृष्टमेव , किन्तु सा सञ्चिका कुत्रास्तीति भ्रमः।

**Comment by indictools** [comment]
saa vyavasthaa idaaniim kalpayitum shakyaa eva.
api.vedavaapi.org idaaniim Ahmedabad server prati preShayati |
tatra apache frontend dvaaraa bhinna services kalpayitum shakyaaH |
No need for custom ports.
- Sai.

2017-05-11 7:39 GMT+05:30 Vishvas Vasuki <notifications@github.com>:

**Comment by vvasuki** [comment]
साध्व् अधुनावगच्छामि। api.vedavaapi.org इत्यत्र textract, grammar इत्यादिश् flaskद्वारा चलिष्यति। 

किन्त्व् अहं पृथक् scala api सेवकम् (server) अपि सम्पर्काशयान्तरे (port) चालयितुमिच्छामि चेद् उपक्षेत्र-सम्पर्काशयस्थान-सम्बन्धम् (subdomain - port mapping ) अन्यं कल्पयितुं शक्ष्यामि तयैव रीत्या, flask-redirect-उपयोगेन वा।
